// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"context"
	"github.com/cloudinary/cloudinary-go/v2"
	"github.com/gin-gonic/gin"
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
	"os"
	"strconv"
	"temukan-api/config"
	"temukan-api/internal/handler"
	"temukan-api/internal/logger"
	"temukan-api/internal/repository"
	"temukan-api/internal/router"
	"temukan-api/internal/service"
	"temukan-api/internal/usecase"
	"temukan-api/internal/worker"
)

// Injectors from wire.go:

func InitializeApp() (*gin.Engine, func(), error) {
	configConfig := config.Load()
	db := config.NewDB(configConfig)
	userRepository := repository.NewUserRepository(db)
	validate := provideValidator()
	userUsecase := usecase.NewUserUsecase(userRepository, validate)
	userHandlerImpl := handler.NewUserHandlerImpl(userUsecase)
	reportRepository := repository.NewReportRepository(db)
	cloudinary, err := config.NewCloudinary()
	if err != nil {
		return nil, nil, err
	}
	matchRepository := repository.NewMatchRepository(db)
	notificationRepository := repository.NewNotificationRepository(db)
	emailService := provideEmailService()
	matchWorker, cleanup, err := provideMatchWorker(reportRepository, matchRepository, notificationRepository, userRepository, emailService)
	if err != nil {
		return nil, nil, err
	}
	reportUsecase := provideReportUsecase(reportRepository, validate, cloudinary, matchWorker)
	reportHandlerImpl := handler.NewReportHandlerImpl(reportUsecase)
	matchUsecase := usecase.NewMatchUsecase(matchRepository)
	matchHandlerImpl := handler.NewMatchHandlerImpl(matchUsecase)
	notificationUsecase := usecase.NewNotificationUsecase(notificationRepository)
	notificationHandlerImpl := handler.NewNotificationHandlerImpl(notificationUsecase)
	engine := router.SetupRouter(userHandlerImpl, reportHandlerImpl, matchHandlerImpl, notificationHandlerImpl)
	return engine, func() {
		cleanup()
	}, nil
}

// wire.go:

var infraSet = wire.NewSet(config.Load, config.NewDB, config.NewCloudinary, provideValidator,
	provideEmailService,
)

var repositorySet = wire.NewSet(repository.NewUserRepository, repository.NewReportRepository, repository.NewMatchRepository, repository.NewNotificationRepository)

var workerSet = wire.NewSet(
	provideMatchWorker,
)

var usecaseSet = wire.NewSet(usecase.NewUserUsecase, provideReportUsecase, usecase.NewMatchUsecase, usecase.NewNotificationUsecase)

var handlerSet = wire.NewSet(handler.NewUserHandlerImpl, wire.Bind(new(handler.UserHandler), new(*handler.UserHandlerImpl)), handler.NewReportHandlerImpl, wire.Bind(new(handler.ReportHandler), new(*handler.ReportHandlerImpl)), handler.NewMatchHandlerImpl, wire.Bind(new(handler.MatchHandler), new(*handler.MatchHandlerImpl)), handler.NewNotificationHandlerImpl, wire.Bind(new(handler.NotificationHandler), new(*handler.NotificationHandlerImpl)))

func provideValidator() *validator.Validate {
	return validator.New()
}

func provideEmailService() *service.EmailService {
	return service.NewEmailService(os.Getenv("RESEND_API_KEY"), os.Getenv("RESEND_FROM_EMAIL"), os.Getenv("APP_URL"))
}

func provideMatchWorker(
	reportRepo repository.ReportRepository,
	matchRepo repository.MatchRepository,
	notifRepo repository.NotificationRepository,
	userRepo repository.UserRepository,
	emailSvc *service.EmailService,
) (*worker.MatchWorker, func(), error) {
	log := logger.Get()

	count := 3
	if v := os.Getenv("WORKER_COUNT"); v != "" {
		if n, err := strconv.Atoi(v); err == nil && n > 0 {
			count = n
		}
	}

	mw := worker.NewMatchWorker(reportRepo, matchRepo, notifRepo, userRepo, emailSvc, count)

	ctx, cancel := context.WithCancel(context.Background())
	go mw.Start(ctx)
	log.Info("match worker started")

	cleanup := func() {
		cancel()
		log.Info("match worker stopped")
	}

	return mw, cleanup, nil
}

func provideReportUsecase(
	repo repository.ReportRepository,
	validate *validator.Validate,
	cld *cloudinary.Cloudinary,
	mw *worker.MatchWorker,
) usecase.ReportUsecase {
	return usecase.NewReportUsecase(repo, validate, cld, mw)
}
